### ISSUE TITLE
Change Event Entity such that it accepts a "date strategy"

### ISSUE THREAD

**Issue by valyippee** [CSC207-UofT/course-project-time#51]
Currently, Event holds a Set of LocalDates, but it should be changed to allow generic repetition of dates, such as "repeat every month".

**Comment by JunruL** [comment]
How about adding repeatingWeekly and repeatingMonthly methods?

**Comment by emilychangg** [comment]
We should also allow for repeating daily. Ex. someone might enter their morning routine

**Comment by ckatsube** [comment]
> How about adding repeatingWeekly and repeatingMonthly methods?

The primary rationale behind applying Strategy pattern is that we apply OOP's polymorphism to the concept of observing some logically connected times. If we were to take the approach of adding methods, the `Event` class (or maybe extracted into another class) would then need to also take in a raw "type" (an enum or String) and then do case/switch heuristics on its type to determine which behavior to apply. On top of that we would have to explicitly add more cases for each new type of behavior we want to add. Heck someone might even have something they want to do every other day.

**Comment by ckatsube** [comment]
The issue I'm currently trying to pound out is how the actual factories for these strategies will work, since just from a glance it seems like their constructors are going to be different (might need a really dirty high level factory :<)

**Comment by ckatsube** [comment]
> The issue I'm currently trying to pound out is how the actual factories for these strategies will work, since just from a glance it seems like their constructors are going to be different (might need a really dirty high level factory :<)

oh and before we get into it, yes there will still be conditional checking to create factories/strategies and whatnot. The objective of the Strategy and Factory patterns are that we extract these dirty details upward where it's easier to make changes rather than in the core of the program which should be the most resistant to changes (because changes here may force large changes in the entire system).
